### ISSUE TITLE
Blog down

### ISSUE THREAD

**Issue by merc1er** [ZonkSec/google-analytics-attack#1]
Your blog is down, can't access the documentation

**Comment by ZonkSec** [comment]
Been on the horn with my hosting provider all morning working out some issues. Should be back up soon.

**Comment by ZonkSec** [comment]
It's back up! Thanks for opening the issue. Be sure to check out the newer version of this tool, its got a lot more features. Don't have a good doc made for it yet, but the con video should contain all the needed info!
